### ISSUE TITLE
TypeError: data type not understood

### ISSUE THREAD

**Issue by druvus** [Emisam/genome_update#1]
I get the following error when I try to start in a fresh folder. 

```
genome_update -g Brucella
Adding new species: Brucella abortus to yaml file
Adding new isolate S19 to species: Brucella abortus
Adding new isolate 2308 to species: Brucella abortus
Adding new isolate 870 to species: Brucella abortus
Adding new isolate 292 to species: Brucella abortus
...
.
...
Adding new isolate CMUL 029 to species: Brucella sp.
Traceback (most recent call last):
  File "/mnt/powervault/bin/conda/bin/genome_update", line 11, in <module>
    sys.exit(main())
  File "/mnt/powervault/bin/conda/lib/python3.5/site-packages/genome_update/__main__.py", line 82, in main
    update_yaml(yaml, NCBI, args.genus, args.species_taxid, args.taxid, args.output, args.input)
  File "/mnt/powervault/bin/conda/lib/python3.5/site-packages/genome_update/__main__.py", line 99, in update_yaml
    dictonary.update_dictonary(isolates, genus)
  File "/mnt/powervault/bin/conda/lib/python3.5/site-packages/genome_update/dictonary_handler.py", line 48, in update_dictonary
    self.handler.write(self.output_path,local)
  File "/mnt/powervault/bin/conda/lib/python3.5/site-packages/genome_update/yaml_handler.py", line 7, in write
    yaml.dump(data,yam)
  File "/mnt/powervault/bin/conda/lib/python3.5/site-packages/yaml/__init__.py", line 200, in dump
    return dump_all([data], stream, Dumper=Dumper, **kwds)
  File "/mnt/powervault/bin/conda/lib/python3.5/site-packages/yaml/__init__.py", line 188, in dump_all
    dumper.represent(data)
  File "/mnt/powervault/bin/conda/lib/python3.5/site-packages/yaml/representer.py", line 26, in represent
    node = self.represent_data(data)
  File "/mnt/powervault/bin/conda/lib/python3.5/site-packages/yaml/representer.py", line 47, in represent_data
    node = self.yaml_representers[data_types[0]](self, data)
  File "/mnt/powervault/bin/conda/lib/python3.5/site-packages/yaml/representer.py", line 203, in represent_dict
    return self.represent_mapping('tag:yaml.org,2002:map', data)
  File "/mnt/powervault/bin/conda/lib/python3.5/site-packages/yaml/representer.py", line 116, in represent_mapping
    node_value = self.represent_data(item_value)
  File "/mnt/powervault/bin/conda/lib/python3.5/site-packages/yaml/representer.py", line 47, in represent_data
    node = self.yaml_representers[data_types[0]](self, data)
  File "/mnt/powervault/bin/conda/lib/python3.5/site-packages/yaml/representer.py", line 203, in represent_dict
    return self.represent_mapping('tag:yaml.org,2002:map', data)
  File "/mnt/powervault/bin/conda/lib/python3.5/site-packages/yaml/representer.py", line 116, in represent_mapping
    node_value = self.represent_data(item_value)
  File "/mnt/powervault/bin/conda/lib/python3.5/site-packages/yaml/representer.py", line 47, in represent_data
    node = self.yaml_representers[data_types[0]](self, data)
  File "/mnt/powervault/bin/conda/lib/python3.5/site-packages/yaml/representer.py", line 203, in represent_dict
    return self.represent_mapping('tag:yaml.org,2002:map', data)
  File "/mnt/powervault/bin/conda/lib/python3.5/site-packages/yaml/representer.py", line 116, in represent_mapping
    node_value = self.represent_data(item_value)
  File "/mnt/powervault/bin/conda/lib/python3.5/site-packages/yaml/representer.py", line 51, in represent_data
    node = self.yaml_multi_representers[data_type](self, data)
  File "/mnt/powervault/bin/conda/lib/python3.5/site-packages/yaml/representer.py", line 342, in represent_object
    return self.represent_sequence(tag+function_name, args)
  File "/mnt/powervault/bin/conda/lib/python3.5/site-packages/yaml/representer.py", line 91, in represent_sequence
    node_item = self.represent_data(item)
  File "/mnt/powervault/bin/conda/lib/python3.5/site-packages/yaml/representer.py", line 33, in represent_data
    if self.ignore_aliases(data):
  File "/mnt/powervault/bin/conda/lib/python3.5/site-packages/yaml/representer.py", line 135, in ignore_aliases
    if data in [None, ()]:
TypeError: data type not understood
```

**Comment by Emisam** [comment]
Currently investigating the issue. It is possible that it occurs when using older versions of dependencies
